"""document sequences

Revision ID: ee047f26f8a1
Revises: e110dcd80310
Create Date: 2026-07-07 14:47:27.966923+00:00

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee047f26f8a1'
down_revision: str | None = 'e110dcd80310'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_sequences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scope_type', sa.String(length=20), nullable=False),
    sa.Column('scope_id', sa.Integer(), nullable=True),
    sa.Column('last_value', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scope_type', 'scope_id', name='uq_document_sequences_scope')
    )
    op.create_index('uq_document_sequences_null_scope', 'document_sequences', ['scope_type'], unique=True, sqlite_where=sa.text('scope_id IS NULL'), postgresql_where=sa.text('scope_id IS NULL'))
    op.add_column('suppliers', sa.Column('company_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_suppliers_company_id'), 'suppliers', ['company_id'], unique=False)
    op.create_foreign_key(None, 'suppliers', 'companies', ['company_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'suppliers', type_='foreignkey')
    op.drop_index(op.f('ix_suppliers_company_id'), table_name='suppliers')
    op.drop_column('suppliers', 'company_id')
    op.drop_index('uq_document_sequences_null_scope', table_name='document_sequences', sqlite_where=sa.text('scope_id IS NULL'), postgresql_where=sa.text('scope_id IS NULL'))
    op.drop_table('document_sequences')
    # ### end Alembic commands ###
