"""initial schema

Revision ID: e110dcd80310
Revises: 
Create Date: 2026-07-07 13:36:13.793461+00:00

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e110dcd80310'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'SUSPENDED', name='company_status'), nullable=False),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_created_at'), 'companies', ['created_at'], unique=False)
    op.create_index(op.f('ix_companies_slug'), 'companies', ['slug'], unique=True)
    op.create_index(op.f('ix_companies_status'), 'companies', ['status'], unique=False)
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('group', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permissions_code'), 'permissions', ['code'], unique=True)
    op.create_index(op.f('ix_permissions_created_at'), 'permissions', ['created_at'], unique=False)
    op.create_index(op.f('ix_permissions_group'), 'permissions', ['group'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_created_at'), 'roles', ['created_at'], unique=False)
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('suppliers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('responsible_person', sa.String(length=150), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suppliers_created_at'), 'suppliers', ['created_at'], unique=False)
    op.create_index(op.f('ix_suppliers_deleted_at'), 'suppliers', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_suppliers_name'), 'suppliers', ['name'], unique=False)
    op.create_index(op.f('ix_suppliers_phone'), 'suppliers', ['phone'], unique=False)
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'name', name='uq_categories_company_name')
    )
    op.create_index(op.f('ix_categories_company_id'), 'categories', ['company_id'], unique=False)
    op.create_index(op.f('ix_categories_created_at'), 'categories', ['created_at'], unique=False)
    op.create_index(op.f('ix_categories_deleted_at'), 'categories', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=False)
    op.create_index('uq_categories_null_company_name', 'categories', ['name'], unique=True, sqlite_where=sa.text('company_id IS NULL'), postgresql_where=sa.text('company_id IS NULL'))
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('customer_type', sa.Enum('INDIVIDUAL', 'LEGAL_ENTITY', name='customer_type'), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('passport', sa.String(length=30), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_company_id'), 'customers', ['company_id'], unique=False)
    op.create_index(op.f('ix_customers_created_at'), 'customers', ['created_at'], unique=False)
    op.create_index(op.f('ix_customers_customer_type'), 'customers', ['customer_type'], unique=False)
    op.create_index(op.f('ix_customers_deleted_at'), 'customers', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_customers_full_name'), 'customers', ['full_name'], unique=False)
    op.create_index(op.f('ix_customers_phone'), 'customers', ['phone'], unique=False)
    op.create_table('payment_methods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('type', sa.Enum('CASH', 'CLICK', 'PAYME', 'BANK', 'DEBT', name='payment_method_type'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'name', name='uq_payment_methods_company_name')
    )
    op.create_index(op.f('ix_payment_methods_company_id'), 'payment_methods', ['company_id'], unique=False)
    op.create_index(op.f('ix_payment_methods_created_at'), 'payment_methods', ['created_at'], unique=False)
    op.create_index(op.f('ix_payment_methods_name'), 'payment_methods', ['name'], unique=False)
    op.create_index(op.f('ix_payment_methods_type'), 'payment_methods', ['type'], unique=False)
    op.create_index('uq_payment_methods_null_company_name', 'payment_methods', ['name'], unique=True, sqlite_where=sa.text('company_id IS NULL'), postgresql_where=sa.text('company_id IS NULL'))
    op.create_table('role_permissions',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'key', name='uq_settings_company_key')
    )
    op.create_index(op.f('ix_settings_company_id'), 'settings', ['company_id'], unique=False)
    op.create_index(op.f('ix_settings_created_at'), 'settings', ['created_at'], unique=False)
    op.create_index(op.f('ix_settings_key'), 'settings', ['key'], unique=False)
    op.create_index('uq_settings_null_company_key', 'settings', ['key'], unique=True, sqlite_where=sa.text('company_id IS NULL'), postgresql_where=sa.text('company_id IS NULL'))
    op.create_table('stores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stores_company_id'), 'stores', ['company_id'], unique=False)
    op.create_index(op.f('ix_stores_created_at'), 'stores', ['created_at'], unique=False)
    op.create_table('units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('short_name', sa.String(length=20), nullable=False),
    sa.Column('conversion_factor', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'name', name='uq_units_company_name')
    )
    op.create_index(op.f('ix_units_company_id'), 'units', ['company_id'], unique=False)
    op.create_index(op.f('ix_units_created_at'), 'units', ['created_at'], unique=False)
    op.create_index(op.f('ix_units_name'), 'units', ['name'], unique=False)
    op.create_index('uq_units_null_company_name', 'units', ['name'], unique=True, sqlite_where=sa.text('company_id IS NULL'), postgresql_where=sa.text('company_id IS NULL'))
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('sku', sa.String(length=60), nullable=False),
    sa.Column('barcode', sa.String(length=60), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('purchase_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('sale_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('min_quantity', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'barcode', name='uq_products_company_barcode'),
    sa.UniqueConstraint('company_id', 'sku', name='uq_products_company_sku')
    )
    op.create_index(op.f('ix_products_barcode'), 'products', ['barcode'], unique=False)
    op.create_index(op.f('ix_products_category_id'), 'products', ['category_id'], unique=False)
    op.create_index(op.f('ix_products_company_id'), 'products', ['company_id'], unique=False)
    op.create_index(op.f('ix_products_created_at'), 'products', ['created_at'], unique=False)
    op.create_index(op.f('ix_products_deleted_at'), 'products', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_products_is_active'), 'products', ['is_active'], unique=False)
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=False)
    op.create_index(op.f('ix_products_quantity'), 'products', ['quantity'], unique=False)
    op.create_index(op.f('ix_products_sku'), 'products', ['sku'], unique=False)
    op.create_index(op.f('ix_products_unit_id'), 'products', ['unit_id'], unique=False)
    op.create_index('uq_products_null_company_barcode', 'products', ['barcode'], unique=True, sqlite_where=sa.text('company_id IS NULL AND barcode IS NOT NULL'), postgresql_where=sa.text('company_id IS NULL AND barcode IS NOT NULL'))
    op.create_index('uq_products_null_company_sku', 'products', ['sku'], unique=True, sqlite_where=sa.text('company_id IS NULL'), postgresql_where=sa.text('company_id IS NULL'))
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('role', sa.Enum('SUPER_ADMIN', 'CEO', 'SELLER', name='user_role'), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('store_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'email', name='uq_users_company_email'),
    sa.UniqueConstraint('company_id', 'username', name='uq_users_company_username')
    )
    op.create_index(op.f('ix_users_company_id'), 'users', ['company_id'], unique=False)
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_deleted_at'), 'users', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_role_id'), 'users', ['role_id'], unique=False)
    op.create_index(op.f('ix_users_store_id'), 'users', ['store_id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.create_index('uq_users_null_company_email', 'users', ['email'], unique=True, sqlite_where=sa.text('company_id IS NULL AND email IS NOT NULL'), postgresql_where=sa.text('company_id IS NULL AND email IS NOT NULL'))
    op.create_index('uq_users_null_company_username', 'users', ['username'], unique=True, sqlite_where=sa.text('company_id IS NULL'), postgresql_where=sa.text('company_id IS NULL'))
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.Enum('LOGIN', 'LOGOUT', 'CREATE', 'UPDATE', 'DELETE', 'STOCK_IN', 'STOCK_OUT', 'SALES_RETURN', 'PAYMENT', 'EXPENSE', 'PRICE_CHANGE', 'LOGIN_FAILED', name='audit_action'), nullable=False),
    sa.Column('entity_type', sa.String(length=60), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('store_id', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('expense_type', sa.Enum('FUEL', 'DRIVER', 'LOADER', 'OTHER', name='expense_type'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('date', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expenses_company_id'), 'expenses', ['company_id'], unique=False)
    op.create_index(op.f('ix_expenses_created_at'), 'expenses', ['created_at'], unique=False)
    op.create_index(op.f('ix_expenses_created_by_id'), 'expenses', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_expenses_date'), 'expenses', ['date'], unique=False)
    op.create_index(op.f('ix_expenses_expense_type'), 'expenses', ['expense_type'], unique=False)
    op.create_index(op.f('ix_expenses_store_id'), 'expenses', ['store_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('stock_ins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=40), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('store_id', sa.Integer(), nullable=True),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'reference', name='uq_stock_ins_company_reference')
    )
    op.create_index(op.f('ix_stock_ins_company_id'), 'stock_ins', ['company_id'], unique=False)
    op.create_index(op.f('ix_stock_ins_created_at'), 'stock_ins', ['created_at'], unique=False)
    op.create_index(op.f('ix_stock_ins_created_by_id'), 'stock_ins', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_stock_ins_date'), 'stock_ins', ['date'], unique=False)
    op.create_index(op.f('ix_stock_ins_reference'), 'stock_ins', ['reference'], unique=False)
    op.create_index(op.f('ix_stock_ins_store_id'), 'stock_ins', ['store_id'], unique=False)
    op.create_index(op.f('ix_stock_ins_supplier_id'), 'stock_ins', ['supplier_id'], unique=False)
    op.create_index('uq_stock_ins_null_company_reference', 'stock_ins', ['reference'], unique=True, sqlite_where=sa.text('company_id IS NULL'), postgresql_where=sa.text('company_id IS NULL'))
    op.create_table('stock_movements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('movement_type', sa.Enum('STOCK_IN', 'SALE', 'SALES_RETURN', 'ADJUSTMENT', name='movement_type'), nullable=False),
    sa.Column('quantity_delta', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('reference_type', sa.String(length=30), nullable=False),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_movements_company_id'), 'stock_movements', ['company_id'], unique=False)
    op.create_index(op.f('ix_stock_movements_created_at'), 'stock_movements', ['created_at'], unique=False)
    op.create_index(op.f('ix_stock_movements_created_by_id'), 'stock_movements', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_stock_movements_movement_type'), 'stock_movements', ['movement_type'], unique=False)
    op.create_index(op.f('ix_stock_movements_product_id'), 'stock_movements', ['product_id'], unique=False)
    op.create_index(op.f('ix_stock_movements_store_id'), 'stock_movements', ['store_id'], unique=False)
    op.create_index('ix_stock_movements_store_product_created', 'stock_movements', ['store_id', 'product_id', 'created_at'], unique=False)
    op.create_table('stock_outs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=40), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('store_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('discount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('paid_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('payment_status', sa.Enum('PAID', 'PARTIAL', 'UNPAID', name='payment_status'), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'reference', name='uq_stock_outs_store_reference')
    )
    op.create_index(op.f('ix_stock_outs_company_id'), 'stock_outs', ['company_id'], unique=False)
    op.create_index(op.f('ix_stock_outs_created_at'), 'stock_outs', ['created_at'], unique=False)
    op.create_index(op.f('ix_stock_outs_created_by_id'), 'stock_outs', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_stock_outs_customer_id'), 'stock_outs', ['customer_id'], unique=False)
    op.create_index(op.f('ix_stock_outs_date'), 'stock_outs', ['date'], unique=False)
    op.create_index(op.f('ix_stock_outs_payment_status'), 'stock_outs', ['payment_status'], unique=False)
    op.create_index(op.f('ix_stock_outs_reference'), 'stock_outs', ['reference'], unique=False)
    op.create_index(op.f('ix_stock_outs_store_id'), 'stock_outs', ['store_id'], unique=False)
    op.create_index('uq_stock_outs_null_store_reference', 'stock_outs', ['reference'], unique=True, sqlite_where=sa.text('store_id IS NULL'), postgresql_where=sa.text('store_id IS NULL'))
    op.create_table('store_stock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'product_id', name='uq_store_stock_store_product')
    )
    op.create_index(op.f('ix_store_stock_product_id'), 'store_stock', ['product_id'], unique=False)
    op.create_index(op.f('ix_store_stock_quantity'), 'store_stock', ['quantity'], unique=False)
    op.create_index(op.f('ix_store_stock_store_id'), 'store_stock', ['store_id'], unique=False)
    op.create_table('debts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('store_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('stock_out_id', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('paid_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('remaining_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('start_date', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'PAID', 'OVERDUE', name='debt_status'), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['stock_out_id'], ['stock_outs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_debts_company_id'), 'debts', ['company_id'], unique=False)
    op.create_index(op.f('ix_debts_created_at'), 'debts', ['created_at'], unique=False)
    op.create_index(op.f('ix_debts_created_by_id'), 'debts', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_debts_customer_id'), 'debts', ['customer_id'], unique=False)
    op.create_index(op.f('ix_debts_due_date'), 'debts', ['due_date'], unique=False)
    op.create_index(op.f('ix_debts_status'), 'debts', ['status'], unique=False)
    op.create_index(op.f('ix_debts_stock_out_id'), 'debts', ['stock_out_id'], unique=True)
    op.create_index(op.f('ix_debts_store_id'), 'debts', ['store_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_out_id', sa.Integer(), nullable=False),
    sa.Column('payment_method_id', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['payment_method_id'], ['payment_methods.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['stock_out_id'], ['stock_outs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_created_at'), 'payments', ['created_at'], unique=False)
    op.create_index(op.f('ix_payments_created_by_id'), 'payments', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_payments_date'), 'payments', ['date'], unique=False)
    op.create_index(op.f('ix_payments_payment_method_id'), 'payments', ['payment_method_id'], unique=False)
    op.create_index(op.f('ix_payments_stock_out_id'), 'payments', ['stock_out_id'], unique=False)
    op.create_table('sales_returns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('store_id', sa.Integer(), nullable=True),
    sa.Column('stock_out_id', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=40), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['stock_out_id'], ['stock_outs.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'reference', name='uq_sales_returns_store_reference')
    )
    op.create_index(op.f('ix_sales_returns_company_id'), 'sales_returns', ['company_id'], unique=False)
    op.create_index(op.f('ix_sales_returns_created_by_id'), 'sales_returns', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_sales_returns_date'), 'sales_returns', ['date'], unique=False)
    op.create_index(op.f('ix_sales_returns_reference'), 'sales_returns', ['reference'], unique=False)
    op.create_index(op.f('ix_sales_returns_stock_out_id'), 'sales_returns', ['stock_out_id'], unique=False)
    op.create_index(op.f('ix_sales_returns_store_id'), 'sales_returns', ['store_id'], unique=False)
    op.create_index('uq_sales_returns_null_store_reference', 'sales_returns', ['reference'], unique=True, sqlite_where=sa.text('store_id IS NULL'), postgresql_where=sa.text('store_id IS NULL'))
    op.create_table('stock_in_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_in_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['stock_in_id'], ['stock_ins.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_in_items_product_id'), 'stock_in_items', ['product_id'], unique=False)
    op.create_index(op.f('ix_stock_in_items_stock_in_id'), 'stock_in_items', ['stock_in_id'], unique=False)
    op.create_table('stock_out_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_out_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('discount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['stock_out_id'], ['stock_outs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_out_items_product_id'), 'stock_out_items', ['product_id'], unique=False)
    op.create_index(op.f('ix_stock_out_items_stock_out_id'), 'stock_out_items', ['stock_out_id'], unique=False)
    op.create_table('debt_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('debt_id', sa.Integer(), nullable=False),
    sa.Column('payment_method_id', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['debt_id'], ['debts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['payment_method_id'], ['payment_methods.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_debt_payments_created_at'), 'debt_payments', ['created_at'], unique=False)
    op.create_index(op.f('ix_debt_payments_created_by_id'), 'debt_payments', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_debt_payments_date'), 'debt_payments', ['date'], unique=False)
    op.create_index(op.f('ix_debt_payments_debt_id'), 'debt_payments', ['debt_id'], unique=False)
    op.create_index(op.f('ix_debt_payments_payment_method_id'), 'debt_payments', ['payment_method_id'], unique=False)
    op.create_table('sales_return_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sales_return_id', sa.Integer(), nullable=False),
    sa.Column('stock_out_item_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sales_return_id'], ['sales_returns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stock_out_item_id'], ['stock_out_items.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_return_items_product_id'), 'sales_return_items', ['product_id'], unique=False)
    op.create_index(op.f('ix_sales_return_items_sales_return_id'), 'sales_return_items', ['sales_return_id'], unique=False)
    op.create_index(op.f('ix_sales_return_items_stock_out_item_id'), 'sales_return_items', ['stock_out_item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sales_return_items_stock_out_item_id'), table_name='sales_return_items')
    op.drop_index(op.f('ix_sales_return_items_sales_return_id'), table_name='sales_return_items')
    op.drop_index(op.f('ix_sales_return_items_product_id'), table_name='sales_return_items')
    op.drop_table('sales_return_items')
    op.drop_index(op.f('ix_debt_payments_payment_method_id'), table_name='debt_payments')
    op.drop_index(op.f('ix_debt_payments_debt_id'), table_name='debt_payments')
    op.drop_index(op.f('ix_debt_payments_date'), table_name='debt_payments')
    op.drop_index(op.f('ix_debt_payments_created_by_id'), table_name='debt_payments')
    op.drop_index(op.f('ix_debt_payments_created_at'), table_name='debt_payments')
    op.drop_table('debt_payments')
    op.drop_index(op.f('ix_stock_out_items_stock_out_id'), table_name='stock_out_items')
    op.drop_index(op.f('ix_stock_out_items_product_id'), table_name='stock_out_items')
    op.drop_table('stock_out_items')
    op.drop_index(op.f('ix_stock_in_items_stock_in_id'), table_name='stock_in_items')
    op.drop_index(op.f('ix_stock_in_items_product_id'), table_name='stock_in_items')
    op.drop_table('stock_in_items')
    op.drop_index('uq_sales_returns_null_store_reference', table_name='sales_returns', sqlite_where=sa.text('store_id IS NULL'), postgresql_where=sa.text('store_id IS NULL'))
    op.drop_index(op.f('ix_sales_returns_store_id'), table_name='sales_returns')
    op.drop_index(op.f('ix_sales_returns_stock_out_id'), table_name='sales_returns')
    op.drop_index(op.f('ix_sales_returns_reference'), table_name='sales_returns')
    op.drop_index(op.f('ix_sales_returns_date'), table_name='sales_returns')
    op.drop_index(op.f('ix_sales_returns_created_by_id'), table_name='sales_returns')
    op.drop_index(op.f('ix_sales_returns_company_id'), table_name='sales_returns')
    op.drop_table('sales_returns')
    op.drop_index(op.f('ix_payments_stock_out_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_payment_method_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_date'), table_name='payments')
    op.drop_index(op.f('ix_payments_created_by_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_created_at'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_debts_store_id'), table_name='debts')
    op.drop_index(op.f('ix_debts_stock_out_id'), table_name='debts')
    op.drop_index(op.f('ix_debts_status'), table_name='debts')
    op.drop_index(op.f('ix_debts_due_date'), table_name='debts')
    op.drop_index(op.f('ix_debts_customer_id'), table_name='debts')
    op.drop_index(op.f('ix_debts_created_by_id'), table_name='debts')
    op.drop_index(op.f('ix_debts_created_at'), table_name='debts')
    op.drop_index(op.f('ix_debts_company_id'), table_name='debts')
    op.drop_table('debts')
    op.drop_index(op.f('ix_store_stock_store_id'), table_name='store_stock')
    op.drop_index(op.f('ix_store_stock_quantity'), table_name='store_stock')
    op.drop_index(op.f('ix_store_stock_product_id'), table_name='store_stock')
    op.drop_table('store_stock')
    op.drop_index('uq_stock_outs_null_store_reference', table_name='stock_outs', sqlite_where=sa.text('store_id IS NULL'), postgresql_where=sa.text('store_id IS NULL'))
    op.drop_index(op.f('ix_stock_outs_store_id'), table_name='stock_outs')
    op.drop_index(op.f('ix_stock_outs_reference'), table_name='stock_outs')
    op.drop_index(op.f('ix_stock_outs_payment_status'), table_name='stock_outs')
    op.drop_index(op.f('ix_stock_outs_date'), table_name='stock_outs')
    op.drop_index(op.f('ix_stock_outs_customer_id'), table_name='stock_outs')
    op.drop_index(op.f('ix_stock_outs_created_by_id'), table_name='stock_outs')
    op.drop_index(op.f('ix_stock_outs_created_at'), table_name='stock_outs')
    op.drop_index(op.f('ix_stock_outs_company_id'), table_name='stock_outs')
    op.drop_table('stock_outs')
    op.drop_index('ix_stock_movements_store_product_created', table_name='stock_movements')
    op.drop_index(op.f('ix_stock_movements_store_id'), table_name='stock_movements')
    op.drop_index(op.f('ix_stock_movements_product_id'), table_name='stock_movements')
    op.drop_index(op.f('ix_stock_movements_movement_type'), table_name='stock_movements')
    op.drop_index(op.f('ix_stock_movements_created_by_id'), table_name='stock_movements')
    op.drop_index(op.f('ix_stock_movements_created_at'), table_name='stock_movements')
    op.drop_index(op.f('ix_stock_movements_company_id'), table_name='stock_movements')
    op.drop_table('stock_movements')
    op.drop_index('uq_stock_ins_null_company_reference', table_name='stock_ins', sqlite_where=sa.text('company_id IS NULL'), postgresql_where=sa.text('company_id IS NULL'))
    op.drop_index(op.f('ix_stock_ins_supplier_id'), table_name='stock_ins')
    op.drop_index(op.f('ix_stock_ins_store_id'), table_name='stock_ins')
    op.drop_index(op.f('ix_stock_ins_reference'), table_name='stock_ins')
    op.drop_index(op.f('ix_stock_ins_date'), table_name='stock_ins')
    op.drop_index(op.f('ix_stock_ins_created_by_id'), table_name='stock_ins')
    op.drop_index(op.f('ix_stock_ins_created_at'), table_name='stock_ins')
    op.drop_index(op.f('ix_stock_ins_company_id'), table_name='stock_ins')
    op.drop_table('stock_ins')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_expenses_store_id'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_expense_type'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_date'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_created_by_id'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_created_at'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_company_id'), table_name='expenses')
    op.drop_table('expenses')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('uq_users_null_company_username', table_name='users', sqlite_where=sa.text('company_id IS NULL'), postgresql_where=sa.text('company_id IS NULL'))
    op.drop_index('uq_users_null_company_email', table_name='users', sqlite_where=sa.text('company_id IS NULL AND email IS NOT NULL'), postgresql_where=sa.text('company_id IS NULL AND email IS NOT NULL'))
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_store_id'), table_name='users')
    op.drop_index(op.f('ix_users_role_id'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_deleted_at'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_index(op.f('ix_users_company_id'), table_name='users')
    op.drop_table('users')
    op.drop_index('uq_products_null_company_sku', table_name='products', sqlite_where=sa.text('company_id IS NULL'), postgresql_where=sa.text('company_id IS NULL'))
    op.drop_index('uq_products_null_company_barcode', table_name='products', sqlite_where=sa.text('company_id IS NULL AND barcode IS NOT NULL'), postgresql_where=sa.text('company_id IS NULL AND barcode IS NOT NULL'))
    op.drop_index(op.f('ix_products_unit_id'), table_name='products')
    op.drop_index(op.f('ix_products_sku'), table_name='products')
    op.drop_index(op.f('ix_products_quantity'), table_name='products')
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.drop_index(op.f('ix_products_is_active'), table_name='products')
    op.drop_index(op.f('ix_products_deleted_at'), table_name='products')
    op.drop_index(op.f('ix_products_created_at'), table_name='products')
    op.drop_index(op.f('ix_products_company_id'), table_name='products')
    op.drop_index(op.f('ix_products_category_id'), table_name='products')
    op.drop_index(op.f('ix_products_barcode'), table_name='products')
    op.drop_table('products')
    op.drop_index('uq_units_null_company_name', table_name='units', sqlite_where=sa.text('company_id IS NULL'), postgresql_where=sa.text('company_id IS NULL'))
    op.drop_index(op.f('ix_units_name'), table_name='units')
    op.drop_index(op.f('ix_units_created_at'), table_name='units')
    op.drop_index(op.f('ix_units_company_id'), table_name='units')
    op.drop_table('units')
    op.drop_index(op.f('ix_stores_created_at'), table_name='stores')
    op.drop_index(op.f('ix_stores_company_id'), table_name='stores')
    op.drop_table('stores')
    op.drop_index('uq_settings_null_company_key', table_name='settings', sqlite_where=sa.text('company_id IS NULL'), postgresql_where=sa.text('company_id IS NULL'))
    op.drop_index(op.f('ix_settings_key'), table_name='settings')
    op.drop_index(op.f('ix_settings_created_at'), table_name='settings')
    op.drop_index(op.f('ix_settings_company_id'), table_name='settings')
    op.drop_table('settings')
    op.drop_table('role_permissions')
    op.drop_index('uq_payment_methods_null_company_name', table_name='payment_methods', sqlite_where=sa.text('company_id IS NULL'), postgresql_where=sa.text('company_id IS NULL'))
    op.drop_index(op.f('ix_payment_methods_type'), table_name='payment_methods')
    op.drop_index(op.f('ix_payment_methods_name'), table_name='payment_methods')
    op.drop_index(op.f('ix_payment_methods_created_at'), table_name='payment_methods')
    op.drop_index(op.f('ix_payment_methods_company_id'), table_name='payment_methods')
    op.drop_table('payment_methods')
    op.drop_index(op.f('ix_customers_phone'), table_name='customers')
    op.drop_index(op.f('ix_customers_full_name'), table_name='customers')
    op.drop_index(op.f('ix_customers_deleted_at'), table_name='customers')
    op.drop_index(op.f('ix_customers_customer_type'), table_name='customers')
    op.drop_index(op.f('ix_customers_created_at'), table_name='customers')
    op.drop_index(op.f('ix_customers_company_id'), table_name='customers')
    op.drop_table('customers')
    op.drop_index('uq_categories_null_company_name', table_name='categories', sqlite_where=sa.text('company_id IS NULL'), postgresql_where=sa.text('company_id IS NULL'))
    op.drop_index(op.f('ix_categories_name'), table_name='categories')
    op.drop_index(op.f('ix_categories_deleted_at'), table_name='categories')
    op.drop_index(op.f('ix_categories_created_at'), table_name='categories')
    op.drop_index(op.f('ix_categories_company_id'), table_name='categories')
    op.drop_table('categories')
    op.drop_index(op.f('ix_suppliers_phone'), table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_name'), table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_deleted_at'), table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_created_at'), table_name='suppliers')
    op.drop_table('suppliers')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_index(op.f('ix_roles_created_at'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_permissions_group'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_created_at'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_code'), table_name='permissions')
    op.drop_table('permissions')
    op.drop_index(op.f('ix_companies_status'), table_name='companies')
    op.drop_index(op.f('ix_companies_slug'), table_name='companies')
    op.drop_index(op.f('ix_companies_created_at'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
